### ISSUE TITLE
New 404's introduced with megamerge

### ISSUE THREAD

**Issue by j00bar** [seekhealing/seekhealing.github.io#106]
It seems like in the refactor, we introduced a number of 404's that we missed. Here's the report from Google:

![image](https://user-images.githubusercontent.com/166664/42011407-47a3d434-7a61-11e8-86b9-09075baa498a.png)

I'll try to help identify where in the site these come from, but let's do what we can to rectify these - thanks!

**Comment by shredtechular** [comment]
So, the refactor re-structured the URLs intentionally so all of the 404s that are seen in the report that end in `*.html` are expected.  As documented in #87 ("Check for CloudFlare redirect support for URL changes") and part of our review meeting of the refactor we did discuss this new behavior and wanted to look into server-side redirect support for moving from the old URLs to the new URLs.  From their [documentation](https://support.cloudflare.com/hc/en-us/articles/200172286-How-do-I-perform-URL-forwarding-or-redirects-with-Cloudflare-) it looks like that should be possible, was there any issues doing the redirects in CloudFare?  If so, I can look into doing in-page redirects in Jekyll but they aren't very graceful and not preferred for the most part.

The item that starts with `_pages/...` is a bug and I can include that fix in a PR.

`asheville-pilot-program/bit.ly/connectAVL` is also another bug that will get fixed.

No idea what `2011/06/the-truth-about-americas-food-why-are-we-so-sick/` is.  Searched the entire site and no mention of that or anything like it in any of the current code.

**Comment by j00bar** [comment]
Thanks - I'd forgotten about the CloudFlare conversation - I'll set that up now.

And thanks for looking into the others!
