### ISSUE TITLE
changes to seekhealing.org/get-involved.html

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#11]
Please change the donate button to this owl:
![donate](https://cloud.githubusercontent.com/assets/25555927/26472402/f4bc09ca-4173-11e7-9ec3-ca1b95bafaa2.png)

**Comment by howtohumanbetter** [comment]
please change the shop button to this owl:
![shop2](https://cloud.githubusercontent.com/assets/25555927/26472422/ff739090-4173-11e7-9f96-73ff60f39eae.jpg)

**Comment by howtohumanbetter** [comment]
please change the volunteer button to this owl:

![i want to help](https://cloud.githubusercontent.com/assets/25555927/26472434/0f7c2f88-4174-11e7-8ab9-4d282242436b.png)

**Comment by howtohumanbetter** [comment]
please make the first donate button link directly to seekhealing.kindful.com

**Comment by howtohumanbetter** [comment]
please change the owl next to the "DONATE TODAY" button to be this owl:

![donate](https://cloud.githubusercontent.com/assets/25555927/26472459/323bf242-4174-11e7-9fe1-4d48e9b3f045.png)

**Comment by howtohumanbetter** [comment]
please change the owl next to the "SHOP NOW" button to be this owl

![shop2](https://cloud.githubusercontent.com/assets/25555927/26472467/41720d32-4174-11e7-9e93-3443ac3fc180.jpg)

**Comment by howtohumanbetter** [comment]
please change the owl next to the "VOLUNTEER TODAY" button to be this owl:

![i want to help](https://cloud.githubusercontent.com/assets/25555927/26472479/52a6221e-4174-11e7-805a-df9b20789408.png)

**Comment by howtohumanbetter** [comment]
please have the "shop now" and "donate today" buttons open new tabs rather than redirect the existing page

**Comment by howtohumanbetter** [comment]
Please add these photos beneath the text in the shop section:

![seekhealing 1](https://cloud.githubusercontent.com/assets/25555927/26472567/ba49bd18-4174-11e7-9d7e-3843ceb76d3b.png)

![watm 1](https://cloud.githubusercontent.com/assets/25555927/26472573/bcd7f996-4174-11e7-9cf5-9e8d43e413fe.png)

![seekhealinglogo](https://cloud.githubusercontent.com/assets/25555927/26472578/c4ecbf90-4174-11e7-9127-bdb13df966bf.jpg)

**Comment by howtohumanbetter** [comment]
Please add this text box beneath the volunteer section:

CURRENTLY RECRUITING VOLUNTEERS WITH THE FOLLOWING SKILLS:
Fundraising
Press relations
Accounting work
Grant writing
SEO & social media marketing
Event planning in DC, Maryland, Virginia, WVA, Tennessee, North or South Carolina

**Comment by shredtechular** [comment]
@j00bar @howtohumanbetter I believe all the changes requested in this item were completed in #46.  I think we can close this issue unless there is something else for this item that you don't see complete?
