### ISSUE TITLE
changes to seekhealing.org/science-of-connection.html

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#12]
Please replace this text:

What does disconnectedness look like socially and behaviorally, and how does it affect the human brain? How can modern science support the concept of a spiritual and social illness?

When human beings are spiritually and socially sick/injured, and we *heal* by connection to a *transcendent nexus*: our personal experience of higher power/nature/source of consciousness. It connotes something that is1) Greater than self, and 2) Exists in a state of connection and interdependence to all elements of an indicidual’s environment. Illness of both the body and mind indicate disconnection and disintegration physically, psychologically, and socially-- from ones self and from one's existential nexus.

with this:

Most people know that medical science considers addiction to be a disease. They say this because we know that the cycle of addiction starts with the brain and gets locked in by the brain. But that’s not the whole story. We know that the brain is plastic, which means that it is constantly being wired and re-wired by the way we experience the world around us. Science tends to think about how technologies like medications or physical brain stimulators can help encourage the brain to rewire itself away from neurological and psychological illness states and towards healthier ones. But we also know that there are some conditions— and addiction is one— where the most effective treatments known are things that help to change thoughts and behavior. 

In studying brain plasticity, we use technology to help put brains in more plastic states. But we’re discovering something very interesting. It turns out that it’s not just about nudging the brain to start rewiring that induces healing— it matters very much what the person is doing when we’re tinkering about in there. What do I mean by this? I mean that the experiences that we have when the brain is primed to change determine what the very effect of that technology has. Our brains are very accommodating. If our thoughts and behaviors give us socially isolating experiences, our brains become set in that mode. But that doesn’t mean that we or our brains work well in that mode. Quite the opposite. 

Let me tell you about another exciting thing that neuroscience is discovering. It turns out that certain brain networks are responsible for more than one type of experience or perception or behavior. And lately, three different sub-fields in neuroscience have come from different directions but recently have found themselves in the same space, zeroing in on this one critical system that’s essential for what they focus on. 

One of the fields is addiction neuroscience. The neuroscience of addiction has long since identified the system responsible for drug and alcohol addiction, called the Reward System. This is the system that is hijacked so effectively by opiates like heroin.  

Another sub-field is neuro-spirituality, or the study of how the brain processes spiritual experiences. It turns out that certain chemical pathways in the reward system are also activated when we have profound experiences of connectedness to something outside of ourselves and greater than ourselves, which makes us feel well and peaceful and whole and joyful. Spiritual experiences tend to create conditions in the brain that look like states where the brain becomes more plastic. In other words, we are starting to suspect that things that trigger spiritual experience herald a brain that can more easily rewire itself.

But the most surprising convergence comes from the field of Social Neuroscience, which studies how our cultural and interpersonal experiences are driven by brain, and why certain experiences have certain effects on the brain. It turns out that the brain system that drives mammals, and especially human, to form social bonds is— you guessed it— the reward system. 

Certain hormones like oxytocin, which people have called the love hormone and the trust hormone, and other chemicals like endorphins and enkephalins, act on parts of those same reward circuits to make social interaction rewarding. This is a system that makes sure that we’re are ok— that we are going to survive as the puny, weak, limited biological creatures that humans are. We form groups, we support each other, we pick up the slack for the more vulnerable members of our group so that the group can get the nourishment it needs to survive and thrive. This system is so important to human survival, and other mammals that need to come together in groups to raise offspring, that we are hardwired to experience pain in the absence of connection.

Let me say that again. The same brain circuit that gives us experiences of profound connectedness also gives us very physical feelings of pain and emotional— even existential— suffering when we don’t have connection to things outside of ourselves. And guess what those physical feelings resemble? Withdrawal from opiates. Stomach upset. Muscle aches. Our skin crawls. We feel restless irritable discontent, and emotionally hopeless about our lives continuing. We feel like we’re dying because the truth is, we ARE dying. 

We tend to think that in modern society, we don’t need tribes of humans to survive, because we have farms that grow food predictably and in luckier places in the world, we came just go to the grocery store to buy food. But the life-threatening epidemics in our society like opiate addictions, or obesity and diabetes from food and sugar addiction, and suicide rates resulting from depression and anxiety and PTSD tell us otherwise. Our society increasingly lacks ways to AUTHENTICALLY connect to other people and to experiences of something transcendent and beyond the boundaries of our small selves and limited minds. This state of affairs acts through the brain’s reward system to make life literally painful. 

That pain drives us to bond to whatever we can. Like food, like electronics, and for too too many people— to drugs. Opiates are the most vicious hijackers of this system because they can directly produce the brain states that social and spiritual connection are supposed to give us. It’s a biological imperative— it is a neural process that is linked to our drive to do things to survive. And people who become addicted feel like they need the objects of their addiction to survive, and it becomes the thing that their strongest behavioral imperative. The drive to get high overwhelms our ability to consider risks of ruin or death. When we are bound to opiates and other drugs, we can’t bond to others, or to anything beyond ourselves. And trapped inside ourselves, we die. Heroin and fentanyl kill us most quickly of all. 

Science has spent a lot of time looking at how technology can save us from the effects of our brains locked in states of addiction and depression, which are states that block us from connecting to anyone or anything else. Seek Healing is one of the first organizations to think differently. With your help, we are creating social and spiritual technologies. We are going to create scalable structures online and in the real world where people can access the spiritual and social connections they need to survive. Medicine can help people detox. But once the physical effects of the addiction fade, we must ensure that people have easily accessible opportunities to connect socially and spiritually— and not just in the confines of our bedrooms on our computers and phones. The systems for spiritual connection and social connection are so overlapping that social connection is a spiritual experience, and spiritual experiences and socially binding. This means we must have SHARED experiences, together, in each other’s company, not just reading words but hearing voices or seeing faces. It means we have to come together for authentic connection. 

Drug Rehab is tragically incomplete unless it is followed by something that boosts connection. Seek Healing is going to fix this problem. And if we are successful, we will be building platforms for connections that can heal a lot of other social epidemics. But first, we need to save the lives of our friends, families, and neighbors who are dying fast from drug overdoses.

**Comment by howtohumanbetter** [comment]
Please add Rachel's headshot and credentials underneath "Neuroscience of Conection and connectedness" and before the new text.

**Comment by howtohumanbetter** [comment]
Please move the science owl to be above "Neuroscience of Connection and connectedness" so that Rachel's headshot and the long text fit underneath it nicely.

**Comment by howtohumanbetter** [comment]
Below "A Spark was Lit" section, please add an "Additional Resources section" and include the following links

- American Carnage article
-

**Comment by shredtechular** [comment]
> Below "A Spark was Lit" section, please add an "Additional Resources section" and include the following links
American Carnage article
PDF's in the external lit research folder of the shared google drive

Can you provide what the URLs for these links?  I'm not really sure what these are?

**Comment by shredtechular** [comment]
Just a note to myself that everything is complete with this issue with the exception of the last line item for the "Additional Resources section".

@howtohumanbetter @j00bar Can you provide links for the "Additional Resources section" or the assets themselves?  Did I miss where you provided these to me?

**Comment by howtohumanbetter** [comment]
Here are the links for the additional resources:

**Comment by howtohumanbetter** [comment]
And now that I'm looking at it, there are actually a couple more changes I want to make to this page. 

1. Next to/Below Rachel's picture, please remove:
Chief Science Officer
Background: Neuroscience PhD, post-doctoral research fellow in the LCNS at the University of Pennsylvania

R&R: development and publication of academic research exploring the neuroscience of addiction behaviors & patterns.

and replace it with: 
**SeekHealing Director of Science**
_Postdoctoral Fellow at the University of Pennsylvania_

Dr. Rachel Wurzman is a Fellow with the Center for Neuroscience and Society, and a Postdoctoral Research Fellow in Neurology with the Laboratory for Cognition and Neural Stimulation at the University of Pennsylvania, Philadelphia, PA, USA. Previously, Rachel served as an Intern in the Science Division of the Office of Science and Technology Policy in the Executive Office of the President of the United States, an Independent Contractor for the World Technology Evaluation Center (dba WTEC, Inc.) in support of the National Nanotechnology Coordinating Center, a Neuroscience Scholar Program Fellow with the Society for Neuroscience, and a Researcher in Residence in the Neuroethics Studies Program of the Pellegrino Center for Clinical Bioethics at Georgetown University. 
 
Rachel is the author of over 20 peer reviewed journal articles and book chapters on various topics in developmental, cognitive, and systems neuroscience, neuroethics, and science policy. Throughout her career, Rachel has investigated neurodevelopmental mechanisms for plasticity in brain circuits whose wiring, and sometimes mis-wiring, contribute to neuropsychiatric disorders on the addiction, obsessive-compulsive, and autistic spectrums. Her current research in the field of neurorehabilitation at the University of Pennsylvania seeks to understand mechanisms for neuroplasticity in brain networks, using non-invasive brain stimulation techniques, neuroimaging, and network neuroscience methods. Additionally, ongoing research in neuroethics addresses the implications of a biopsychosocial and systems-oriented perspective on neuropsychiatric spectrum phenomena (such as addiction) for research, treatment, and social policy.

Rachel received her PhD in Neuroscience from Georgetown University’s Interdisciplinary Program in Neuroscience, where her she was an NIH Ruth L. Kirschstein National Research Service Award Fellow. She received her M.S. in Physiology and Biophysics from Georgetown University, and her B.A. in Neuroscience from Smith College. 

then insert another little line divider before the long text that begins with "Most people know that..."
