### ISSUE TITLE
changes to seekhealing.org/board-of-directors.html

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#14]
Please add a photo for Joshua

**Comment by howtohumanbetter** [comment]
please change Kyla's photo to:

**Comment by howtohumanbetter** [comment]
add "100% volunteer" beneath the words "Board of Directors"

**Comment by howtohumanbetter** [comment]
Beneath the Title and Subtitle (Board of Directors, 100% Volunteer), please add a gauge that shows total hours invested by Board and total $ donated by Board (with a "last updated" timestamp)
let me know when you add this and I will tell you what current numbers are

**Comment by howtohumanbetter** [comment]
change Kyla's title to Director of Development

**Comment by howtohumanbetter** [comment]
change Rachel's title to Director of Science

**Comment by howtohumanbetter** [comment]
change Joshua's title to Director of Technology

**Comment by howtohumanbetter** [comment]
change "R&R" in each blurb to: "Responsibilities"

**Comment by howtohumanbetter** [comment]
change Jennifer Responsibilities from:
interface management, strategic decision-making

to:
strategic vision, interface management, strategic networking, capital fundraising, SeekConnection program oversight

**Comment by howtohumanbetter** [comment]
change Kyla Responsibilities from:
fundraising and business operations

to:
sustaining fundraising (events, crowdfunding, monthly memberships, merchandise sales), financial oversight

**Comment by shredtechular** [comment]
The first line item in this task says:

> Please add a photo for Joshua

Is there an image that you would like me to use here?  Or should I ignore this for now?

**Comment by howtohumanbetter** [comment]
I'll get one from him. We also need to remove Amanda Straughn from the Board of Directors page.

**Comment by howtohumanbetter** [comment]
@shredtechular please remove Amanda Straughn from this page, so there will just be the 4 Board members.
