### ISSUE TITLE
Oct 2018: Navigation and new pages

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#144]
![image](https://user-images.githubusercontent.com/25555927/47518005-cd204a80-d857-11e8-87cf-3a89d26f93d5.png)

**Comment by howtohumanbetter** [comment]
Hey @shredtechular  -- just making sure we're on the same page, I didn't mean that the actual hover menus need to look like this. This is just my understanding of the sitemap. I don't think there are/will be any sub-sub menus: just posted this first so you could see where the new pages would go. It's all still two levels. (except for rat park experiments, which was already there)

**Comment by shredtechular** [comment]
Ohh, okay, I completely misunderstood this one then @howtohumanbetter .  Sorry about that.  So, this would only be to change the order of the top level menus, got it...

**Comment by shredtechular** [comment]
You mention to add the "Additional Resources" page to the Learn landing page as a 4th button.  Is there an image you want to use for this?  Do you want to use the book image that you put in the issue for the Additional Resources maybe?  Would that make sense?

**Comment by secureli** [comment]
Could I get some clarification on remaining tasks for this issue?

**Comment by howtohumanbetter** [comment]
@shredtechular that sounds right to me! 

1. how about a little point and click icon like this
![image](https://user-images.githubusercontent.com/25555927/50778244-7679b880-126b-11e9-866f-3ee6a7699db3.png)


2. That's fine
