### ISSUE TITLE
Oct 2018: The Science of Connection updates

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#149]
Please replace the TEDx video link with the new TED.com link:
https://www.ted.com/talks/rachel_wurzman_how_isolation_fuels_opioid_addiction/discussion

Please remove Rachel and Gabor’s bios, so that the text beginning with “Most people know that medical science considers addiction to be a disease…” begins right under “Research Study: Blocking opioids attenuates physical warmth-induced feelings of social connection”

Please keep the links to Additional Resources and Rat Park experiments at the bottom of this page, but remove the “Spark Was Lit” button

**Comment by shredtechular** [comment]
When you say:

> Please replace the TEDx video link with the new TED.com link:
https://www.ted.com/talks/rachel_wurzman_how_isolation_fuels_opioid_addiction/discussion

I assume you mean to replace the video on the page AND the link underneath to point to the ted.com video & page, right?  So, not just replace the link per se?

Also, Does the text underneath the video need to change at all?  It currently says:

> Disconnected Brains: How isolation fuels opioid addiction
> Dr. Rachel Wurzman, TEDxMidAtlantic, October 2017

I assume at a minimum we should change "2017" to "2018" right?  Is all the other text the same I think?

**Comment by secureli** [comment]
see https://github.com/secureli/seekhealing.github.io/tree/issue-149 - not sure how to deal with the spacing issue above “Most people know that medical science considers addiction to be a disease…

**Comment by howtohumanbetter** [comment]
@j00bar this one.

Andrew's clarifications are correct -- 2017 should change to 2018 and please specify TED not TEDx.
