### ISSUE TITLE
please optimize entire site for mobile.

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#15]
there are multiple issues on most pages

**Comment by lucb202** [comment]
If you can be more specific, that would help

**Comment by howtohumanbetter** [comment]
Homepage: content is not aligned (of the three sections, first is right aligned, next is left aligned, last is center aligned -- it feels a little jarring) 

seems like there should be more spacing between SeekHealing logo and the hero text + video. Maybe the Logo font size should be smaller, or the hero text should be smaller - not sure, but it looks like they're competing being the same size.

**Comment by howtohumanbetter** [comment]
why-we-care:
the words show up one or two on each line in the first section
the pictures are too large

**Comment by howtohumanbetter** [comment]
rethinking-rehab:
the first two post-it notes show up on top of each other
(but don't optimize until @j00bar makes the content changes, there's another open issue to drop the animation here/change the post-it note graphics)

the third post-it note is mis-aligned

the pictures are too big

some sections show up with only one word per line

the graphics under "Longterm healing is rare because most options make people feel even lonelier" are a bit messed up: the spacing between them is too much, and the molecule is overlaid on top of the prison icon

In the "addiction is an adaptation" quote overlay: the picture is too big, and the words "addiction" and "adaptation" are hard to read because they overlap with the quotation mark
^same with the "we are the medicine" quote overlay at the end

**Comment by howtohumanbetter** [comment]
science-of-connection:

long sections of text show up with only one word per line or only 3 words per line

**Comment by howtohumanbetter** [comment]
this is what I mean by sections that show up with only a few words per line:
![image uploaded from ios 3](https://cloud.githubusercontent.com/assets/25555927/26744485/6b207b64-47e6-11e7-82cc-28b9d171dfd9.jpg)

**Comment by howtohumanbetter** [comment]
hope this helps @lucb202 , I'm gonna hold off posting more specific comments until @j00bar closes the other issues though because maybe things will change!

**Comment by j00bar** [comment]
The few words per line appears to be that Lucy specified `col-xs-2 col-xs-offset-2` when I think she meant `col-xs-12 col-xs-offset-2`. I've fixed that as part of #24.
