### ISSUE TITLE
Oct 2018: A Spark Was Lit updates

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#151]
Please take down this page and move the text to a blog post by Dr. Rachel Wurzman’s (under “Blog”)

**Comment by secureli** [comment]
https://seekhealing.org/blog/ appears empty - can you clarify where this text should be moved to?

**Comment by j00bar** [comment]
@howtohumanbetter Pending creation of a blog section, what do you want to happen here?

**Comment by howtohumanbetter** [comment]
@j00bar just remove it. Thank you.
