### ISSUE TITLE
Oct 2018: redirect request

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#159]
Can you please make it so that if someone types in or links to seekhealing.org/heal, it goes to the new "How SeekHealing Works" page? That should be the landing page for the HEAL menu, anyway.

**Comment by j00bar** [comment]
@shredtechular If you don't want to do it with a meta refresh, I can see if we have the ability to do it in CloudFlare with our plan.

**Comment by shredtechular** [comment]
@j00bar As this is a new page, I think we can simply make this page's permalink `/heal` so I don't think we need any redirect here at all at this point.  I think the takeaway here is just to make the new page's (How SeekHealing Works) permalink `/heal`.  Maybe I'm missing something, but I think we should be okay here, but I will definitely let you know if I have any issues with that once I dig in on that page, sound good?

**Comment by howtohumanbetter** [comment]
@j00bar @shredtechular that makes sense :) sometimes I'm one or two crayons short of a full set ...
