### ISSUE TITLE
Oct 2018: Donate (new page)

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#160]
Please make a new page here.

Title: Donate Now

Image below: Donate owl.png
![donate owl](https://user-images.githubusercontent.com/25555927/47526027-956fcd80-d86c-11e8-92f6-e4b36ba71d6a.png)

3 white boxes (like the ones on the Contact Us page, but replace location icon with a dollar sign)

Box 1:
MEMORIAL DONATION
Smaller italic font below: Make a donation in the name of a loved one you lost to overdose or drug poisoning.
Link to: https://seekhealing.kindful.com/?campaign=263108

Box 2:
GENERAL DONATION
Smaller italic font below: Connect with people who are at risk for overdose and help provide free support services to anyone at any stage in the addiction healing process.
Link to: https://seekhealing.kindful.com/?campaign=339304

Box 2:
MONTHLY FOUNDER’S CLUB
Smaller italic font below: Help us make the SeekHealing project sustainable by making a monthly contribution.
Link to: https://seekhealing.kindful.com/?campaign=264477

**Comment by j00bar** [comment]
@howtohumanbetter There are also these, if those interest you? https://support.kindful.com/hc/en-us/articles/115004950467-Creating-a-Donation-Plugin

**Comment by howtohumanbetter** [comment]
Oh yea great thanks @j00bar ! Honestly whichever is easier for you/requires less time @shredtechular

**Comment by howtohumanbetter** [comment]
This one is a high priority
