### ISSUE TITLE
Oct 2018: Press page updates

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#168]
Please remove Rachel’s TEDx talk from this page

Please add: “Mountain Xpress: Kiss and say goodbye: Addressing the real cause of addiction”
https://mountainx.com/opinion/kiss-and-say-goodbye-addressing-the-real-cause-of-addiction/ 
image:
![mountain xpress logo](https://user-images.githubusercontent.com/25555927/47526353-84738c00-d86d-11e8-97d0-a7598bf716c2.png)

Please add: “The Blue Banner: Harm reduction tactics used to help drug users”
http://thebluebanner.net/harm-reduction-tactics-used-to-help-drug-users/ 
image:
![ioad big](https://user-images.githubusercontent.com/25555927/47526363-89384000-d86d-11e8-8169-6a7731e6ac87.jpg)

Please add “Asheville FM News Team Speaks With Seek Healing”
https://www.ashevillefm.org/post/afm-news-team-speaks-with-seek-healing/ 
image:
![asheville fm logo](https://user-images.githubusercontent.com/25555927/47526370-8ccbc700-d86d-11e8-9389-aa293d819b08.jpeg)

Please add “iHeartRadio WWNC Changes: Overdose Awareness Day 2018”
https://www.iheart.com/podcast/139-changes-28012724/episode/overdose-awareness-day-29816901/?autoplay=true&cmp=ios_share
image:
![wwnc logo](https://user-images.githubusercontent.com/25555927/47526378-92291180-d86d-11e8-9711-121b84f22143.jpeg)

Please change:
iHeartRadio interview with SeekHealing Executive Director, Jennifer Nicolaisen
To:
iHeartRadio: Drug Addiction Relapses – SeekHealing

Please change:
Import This Podcast Interview with SeekHealing Executive Director, Jennifer Nicolaisen
To:
Import This Podcast: Jennifer Nicolaisen on Addiction, SeekHealing Non-Profit, Etc.

**Comment by j00bar** [comment]
@howtohumanbetter The iHeartRadio link is no longer online?
