### ISSUE TITLE
little fixes to recent homepage updates

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#183]
Homepage:

Please add a grey line (similar to the one that is below the image of the four owls) above the Johann Hari quote and below "SeekHealing is a 501(c)3 non-profit serving people at risk for overdose. We provide free support services to anyone at any stage in the addiction healing process."

Is it possible to make these bullet points have check marks in them?:
- Public harm reduction education: training in overdose reversal and redefining addiction
- Open door policy: current drug users, abstinence-only, & medication-assisted treatment all welcome
- Ongoing support: pairing with trained volunteers, community activities, & therapeutic services
- Training in authentic connection: how to better listen to others and yourself
- Community re-integration: see “How SeekHealing Works”

Please also change the wording of the check mark mark bullet points as follows:
- Public harm reduction education: training in overdose reversal and redefining addiction
- Community treatment program: see “How SeekHealing Works” (PLEASE LINK THE WORDS "How SeekHealing Works" TO "Heal"
- Open door policy: current drug users, abstinence-only, & medication-assisted treatment all welcome
- Ongoing support: pairing with trained volunteers, community activities, & therapeutic services
- Training in authentic connection: how to better listen to others and yourself

Please change the brochure to this file:

Please highlight and boldface the word "SeekHealing" in Gabor Mate's quote

Would it be possible to make the 6 buttons for "What do you want to do" equal size circles/bubbles, rather than different sized rectangles?

Can you please make all the logos at the bottom the same size (all the same height), put them in a single column, and add text below each on that links to the same site as the logo:
Buncombe County District Attorney's Office
Goodwill
Justice Resource Center
Mission Health
Buncombe Health and Human Services
C3-356 Peer Living Room

**Comment by j00bar** [comment]
@howtohumanbetter You reference a file for the brochure, but do not provide it.

**Comment by j00bar** [comment]
@howtohumanbetter I need higher quality assets for the partner logos if I'm going to lay them out as you wish. The BCHHS asset, for example, is only 50 pixels wide...

**Comment by howtohumanbetter** [comment]
Goodwill large logo image:
![goodwill logo large](https://user-images.githubusercontent.com/25555927/47868540-cc009780-ddda-11e8-8b62-0e7ddbab5e43.png)

BCHHS large square logo:
![untitled design 99](https://user-images.githubusercontent.com/25555927/47868514-b5f2d700-ddda-11e8-8956-5c99ab67ad90.png)

C3-356 square image:
![c3356 square](https://user-images.githubusercontent.com/25555927/47868833-acb63a00-dddb-11e8-9437-70d7c6cb6b60.png)


Mission health square image:
![square mission health](https://user-images.githubusercontent.com/25555927/47868832-a9bb4980-dddb-11e8-9c81-8ed553ff2dbc.png)

**Comment by howtohumanbetter** [comment]
brochure file:
[About SeekHealing_Nov2018.pdf](https://github.com/seekhealing/seekhealing.github.io/files/2539666/About.SeekHealing_Nov2018.pdf)
