### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#190]
![image](https://user-images.githubusercontent.com/25555927/47880684-4096fe80-ddfa-11e8-8a57-41c1b9d476d4.png)

The main blurb should say: “Healing from addiction through connection.”

Asheville Pilot Program needs to not say “purple stick figures.” And it should not have the word "pilot"

SeekHealing Programs should not be linked from here. This page should be hidden -- it is not currently linked anywhere in the site nav.

**Comment by shredtechular** [comment]
I believe the "purple stick figures" is gone now with the latest updates, so that part is N/A now.

Question: when you say the "main blurb" are you saying that instead of:

> SeekHealing, Rethink Rehab

it should say,

> SeekHealing, Healing from addiction through connection

Is that what you would like?

**Comment by secureli** [comment]
<img width="573" alt="screen shot 2018-12-16 at 3 54 00 pm" src="https://user-images.githubusercontent.com/10089608/50058747-d4beea00-014a-11e9-9e54-e3a06043181b.png">

This appears to be resolved. Please provide feedback or close ticket.

**Comment by j00bar** [comment]
@howtohumanbetter This waiting for you now.

**Comment by howtohumanbetter** [comment]
new blurb below main heading:
SeekHealing is a 501(c)3 non-profit serving people at risk for overdose. We provide free support services to anyone at any stage in the addiction healing process.

**Comment by howtohumanbetter** [comment]
and pls remove link to "seekhealing programs"
