### ISSUE TITLE
Moderate content changes to the Listening Training page

### ISSUE THREAD

**Issue by j00bar** [seekhealing/seekhealing.github.io#209]
1. Above the Pema Chodron quote and below the little line, add:

> Join us for 16 hours of professional training in authentic human connection and peer-based addiction support. It’s a one-of-a-kind opportunity to dig deeper into your own personal growth & healing journey while lifting others up along the way.
>
> (Italicized) And below that, in smaller, italicized font, please add:
Listening Training is provided free of cost by SeekHealing, a 501(c)3 nonprofit. The program is entirely donation based. A donation is not required but greatly appreciated.

2. Replace the Pema Chodron quote with this image: 
![image](https://user-images.githubusercontent.com/166664/49257944-b20da100-f3e8-11e8-97ba-f9158b18eec7.png)

3. Change the bullet points below the quote to:

* harm reduction for addiction
* understanding how harm reduction applies to recovery
* redefining addiction
* destigmatizing addiction
* eliminating shame in conversation
* interacting with more empathy
* relating with others more authentically
* using nonviolent communication techniques
* setting compassionate boundaries
* providing peer-support for addiction recovery

4. Please change the "By completing this training, ... at the community level" section to: 

> By completing this training, you’ll become part of a radically different addiction treatment program in Buncombe County, NC. The disease of addiction shows up in individuals because it is first a disease of the community: a problem with how individuals within a group relate with one another. SeekHealing “treats” addiction disease at the community level.

5. Please change the sentence "It will also teach you..." to:

> It will also teach you how to better listen to yourself and identify your own needs, whether you struggle with substance use or some other type of addiction.

6. Please change the clause "and you'll also have access to..." to:

> and you’ll also have access to all kinds of awesome, donation-based groups, meetings and activities to explore with other people in the community.

7. Please change the text "Listening training is provided by... but greatly appreciated" to:

> Listening Training is provided free of cost by SeekHealing, a 501(c)3 nonprofit. The program is entirely donation based. A donation is not required but greatly appreciated.

8. Please change the structured text "Help liberate yourself... in a meaningful way" to:

> Whether you want to:
> volunteer to fight the overdose crisis
> live a more connected life
> isolate yourself less
> work on your long-term recovery
> stay on course after a recent detox
> ... this program is for you!

9. Please remove the section "This 16 hour course split between two days includes:"

10. Please change the volunteer commitments section to read:

> 1-2 hour in-person meeting with your person-pair every week
> 1-2 hours of availability with your person-pair throughout the week for texting and phone-calls at your convenience
> Gathering with other pairs, once per month
> Regularly attending socials, group activities and meetings with other people in the community

https://seekhealing.slack.com/archives/CE76SU751/p1543449698000400
https://seekhealing.slack.com/archives/CE76SU751/p1543449700000600

**Comment by secureli** [comment]
It doesn't appear that I have the ability to assign this task to myself, yet.

**Comment by j00bar** [comment]
@shredtechular If you'd please go ahead and take this one.
