### ISSUE TITLE
Moderate content changes to the Extra Care Program Page

### ISSUE THREAD

**Issue by j00bar** [seekhealing/seekhealing.github.io#211]
1. Below the little line and above the picture, please add:

> If you’re currently trying to make a major change to your relationship with a certain drug or chemical, you may qualify for SeekHealing’s Extra Care Program scholarships.

2. Below the picture, please add **_(styling notes inline)_**:

> Whether you are:
> a current drug user
> trying to stay 100% abstinent
> trying to moderate
> on medication assisted treatment (MAT) like suboxone or methadone
> you’re welcome in this program.
> 
> The only requirement is that you’re a Seeker. (please make the word Seeker the bold and italic style)
> 
> seek·er |ˈsēkər | noun: (please make this line bold typeface)
> a human being who has committed to constantly re-evaluating their relationship with chemicals and/or behaviors that don’t serve them.

3. Please add a full-width dark banner that reads **_(styling notes inline)_** :

> SeekHealing is a community-sourced treatment model that empowers you to heal rather than achieve certain outcomes. (please make the words SeekHealing in this sentence the bold italic typeface)

4. Please replace the list of "gone through detox... in sober living housing" with **_(styling notes inline)_**:

> survived an overdose
> gone through detox one or more times
> home detox, medical detox, ibogaine-assisted detox, or other detox
> participated in an addiction treatment program
> resided in sober living housing
> had any other kind of addiction crisis
> (note: these should all be separate bullet points, except for the line with the different kinds of detoxes, which should be below the bullet above it in smaller, italicized font)

5. Please change the "Your may qualify for..." sentence to:

> You may qualify for SeekHealing’s extra care program to receive free, ongoing support as you navigate this major life transition.

6. Please change the "Currently only available locally... does not provide transportation" section to:

> Scholarships available. Currently only available locally in Asheville, NC. Limited capacity. Program is non-residential and does not provide transportation.

7. Below the disclaimer in 6, add a heading "How It Works"

8. Please change the paragraph "As a seeker in the SeekHealing program... getting their connection needs met" to:

> As a seeker in the SeekHealing program, we’ll get you paired up to meet with someone once a week in order to practice a more meaningful type of social connection. If you’re working the steps, your SeekHealing person will be a nice complement to having a sponsor: unlike a sponsor, your person will not give you any specific advice or instructions for your recovery. They will be just another seeker like you. They may have substance use history, or they may not, but either way they have made a commitment to being more intentional about getting their connection needs met (just like you have by joining this program).

9. Below the image+text block for 1-on-1 meetings with another seeker, please add another using an image (to be provided later) and the following text:

> We’ll also get you signed up for our Listening Training, which is a two-day professional workshop to teach you the art of authentic connection. It’s about learning how to listen better first to yourself, so that you can listen better to others. Listening Training is a one-of-a-kind opportunity to dig deeper into your own personal growth & healing journey while lifting others up along the way. The training will help you break down the barriers that keep conversation superficial and that make relationships feel unfulfilling or frustrating. You will learn how take the lead in having a real, no-strings-attached conversation with other people - whenever you want.

10. Below that, please add another image+text block using an image (to be provided later) and the following text:

> Having (actual) fun is probably the most important part of all this. We host an almost constant stream of social events and gatherings, so that as part of working the program, folks in the community will be reaching out to invite you to come to games nights, potlucks, holiday parties, concerts, cooking parties, wig parties ... it gets weirder, but we’ll let you find that out for yourself. The point is, you’ll be surrounded by opportunities to come hang out and connect in a trigger-free environment with other people who are there because they want to connect, too. Sometimes you need a break from recovery and talking about drug use so that you can actually recover.

11. Please replace the content for the two paragraphs beginning "Things like hiking..." and "SeekHealing will cover..." with these two:

> Our program management staff will work with you 1-on-1 to help you explore things like hiking, yoga, foraging, meditation, martial arts, dance, aerial arts, gardening, horseback riding, painting, animal healing touch, Reiki, 12 step groups, alternative recovery groups, slack-lining, sports leagues, nutritional counseling, and more.
>
> SeekHealing will cover any fees associated with getting signed up for these things, and our team will work with you on the scheduling (and remind you when you have an appointment coming up, and remind you again just in case). We’ll help you figure out how you’re going to get there (although we can’t provide actual transportation), and we’ll also have a conversation with you about what you do and don’t like, so you’re not obligated to continue doing any one thing. The point is to explore and find something you like and that helps you feel really connected.

12. Please replace the paragraph starting with "Your scholarship through... EMDR therapy and more" with:

> Your scholarship through the extra care program will also pay for you to get access to direct therapeutic services, including but not limited to: therapy, bodywork, acupuncture, nutritional counseling, chiropractic, trauma-healing, spiritual counseling, intuitive counseling, energy healing, EMDR therapy, and more. Again, our team will work with you to schedule your appointment, remind you about it, make sure you get there, and follow up with you to process it afterwards.

13. Please repeat the instructions in 6 for the subsequent disclaimer.

https://seekhealing.slack.com/archives/CE76SU751/p1543530259002800
https://seekhealing.slack.com/archives/CE76SU751/p1543530304003500
https://seekhealing.slack.com/archives/CE76SU751/p1543530308003700

**Comment by secureli** [comment]
Regarding #3 - Please add a full-width dark banner that reads (styling notes inline) - what is the styling code for this?

**Comment by j00bar** [comment]
@secureli HTML tags for bold and italic, like: 

`<strong><em>This is bold-italic</em></strong> and this isn't`
<strong><em>This is bold-italic</em></strong> and this isn't

**Comment by secureli** [comment]
@j00bar understood - but for a "full width dark banner", how can this be achieved?
