### ISSUE TITLE
changes to http://seekhealing.org/our-programs.html

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#27]
please remove the "owls, whatever" from the image

**Comment by howtohumanbetter** [comment]
![humans who can help each other](https://user-images.githubusercontent.com/25555927/27145655-d3ebd14e-5136-11e7-9d4b-4f9abaaa8b2a.jpg)

**Comment by howtohumanbetter** [comment]
change the content on this page to reflect the content in these slides:
[seekhealing core slides.pptx](https://github.com/seekhealing/seekhealing.github.io/files/1322015/seekhealing.core.slides.pptx)

here are the image files for just the first two slides:
<img width="1151" alt="corebizgraphic2" src="https://user-images.githubusercontent.com/25555927/30706981-0b3adf26-9ec8-11e7-97f4-c8c0eccf6253.png">
<img width="1149" alt="corebizgraphic1" src="https://user-images.githubusercontent.com/25555927/30706982-0b43903a-9ec8-11e7-9dfa-b4af7aea91a7.png">

**Comment by howtohumanbetter** [comment]
![healing hubs logo no slogan](https://user-images.githubusercontent.com/25555927/30707053-3f0a20a0-9ec8-11e7-9724-1c99d7c1e210.png)
![seekconnection logo no slogan](https://user-images.githubusercontent.com/25555927/30707077-4fe633c8-9ec8-11e7-84a8-8ae6f138b744.png)

**Comment by howtohumanbetter** [comment]
core program elements:
peer-based therapy between people who have diverse mental health experiences 
(not limited to substance use disorders (SUDs)
+
guided exposure to new experiences, communities, jobs, hobbies, practices, activities 
+
scalable technology platform
+
grassroots affiliate network

= SeekConnection
= Healing Hubs



Because authentic connection is symbiotic, SeekHealing delivers enhanced neuroplasticity and integrated mental health benefits to each of the user groups who are involved in the healing network. The feelings of loneliness and disconnectedness experienced post-detox are analogous to those experienced during and after common, major life transitions. Our platform creates a pipeline for authentic connections to occur between humans seeking better mental health in different contexts: 
after detox from active addiction: seekers
after a major life transition; like retirement, mental illness recovery, academic graduation, or targeted career development: listeners
as representatives for communities and businesses that promote healing through connection: connection agents
In this way, the SeekHealing model provides both direct, measurable benefits to health of the SUD-affected population and indirect benefits to the wider population.

**Comment by howtohumanbetter** [comment]
@shredtacular, when you get to this one I think it would be best for us to set up a quick call or chat to discuss. I think there is a better way to present this information but I'm not sure how.

**Comment by shredtechular** [comment]
OK, got it, I'll hold onto this one until we can knock out a few of the others first unless this is a priority.
