### ISSUE TITLE
add new page: Best Practices for Detox

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#30]
a landing page that has an article (written by me) with basic best practices for nutrition, thiungs to do, etc. then it offers menu leading to the following sub-pages:
- nutrition
- kratom
- iboga
- 12 steps
- connection library

**Comment by shredtechular** [comment]
When you say "landing page" do you mean create a new page that is navigated to from the top main menu and has a submenu with the items that you listed?  Something like:

<kbd>
<img width="239" alt="screen shot 2017-10-08 at 1 51 55 pm" src="https://user-images.githubusercontent.com/2396774/31319363-f90916fe-ac2f-11e7-800e-9a8f26daf30c.png">

</kbd>

**Comment by howtohumanbetter** [comment]
@shredtechular thank you for mocking this up. I actually have a better idea:

In the top main menu, please change "Our Programs" to "Heal" with the following menu items: "Our Programs", "Guidance for Detox", and "SeekConnection."

"Our Programs" page is ... what is now (although I know it needs work, will address that in the corresponding appropriate issue)

"Guidance for Detox" and "SeekConnection" pages can just say "Coming soon..." for now, please.

Thank you!

**Comment by howtohumanbetter** [comment]
@shredtechular along this same line, please also change "Stay Connected" in the top main menu to simply "Connect." Please also change "Get Involved" to "Help" 

That way the top main menu options will read: Learn / Heal / Help / Connect / About Us
