### ISSUE TITLE
add page: connection agent registration form

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#31]
google form with database dump

**Comment by shredtechular** [comment]
Do you have a google form setup for this task already?  If not, is what fields are desired in this form?

**Comment by howtohumanbetter** [comment]
@shredtechular let me get back to you on this. The form has evolved quite a lot since I first posted this issue. Let's deprioritize for now

**Comment by howtohumanbetter** [comment]
[connection agent registration form3.docx](https://github.com/seekhealing/seekhealing.github.io/files/1475377/connection.agent.registration.form3.docx)

**Comment by howtohumanbetter** [comment]
this should go under the "Help" menu as its own page: "Connection Agents"
