### ISSUE TITLE
small changes to landing page

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#32]
**change** "not a cure" to "rethink rehab" (shows up in the page title on the tab, when you link it, etc)

**change:**
Unlocking the benefits of authentic connection experiences to empower sustainable healing after detox from heroin & opioid addiction.
**to:**
Detox aftercare services that liberate human beings from opioid addiction relapse.

**Add the following Rumi quote below the hero and above the "SeekConnection Fundraising Drive"**
I have been a seeker and still am
but I stopped asking the books and the stars.
I started listening to the teaching of my soul.
- Rumi

**change this:**
SeekHealing is a detox aftercare model that unlocks the neurochemical benefits of authentic connection experiences. This non-profit organization provides equal-opportunity programs that use principles of connection & community to facilitate sustainable healing after detox from opioid & heroin addiction.
**to this, in a slightly larger font:**
A detox aftercare model that unlocks the neurochemical benefits of authentic connection experiences. This non-profit organization provides equal-opportunity programs that use principles of connection & community to empower sustainable healing after detox from opioid & heroin addiction.
**then please add another little divider line and then this, in a slightly smaller font:**
Founded in 2016, SeekHealing is a 501(c)3 charity and post-detox recovery model that challenges mainstream stigmas about opioid and heroin addiction. Our programs turn the idea of standard rehab upside down by providing affordable services that prioritize authentic connection and harm reduction. 

Our programs are designed for the 6-12 months after detox that are most critical to sustainable recovery and mental health integration. The methodology is focused to enhance the neuroplasticity of participants through: intentional experiences of authentic social & spiritual connection; rewarding the practice of learning new things; and facilitating a major change to their daily environment. 

Program features include peer-based therapy, personalized community & career transitions, and guidance through intentional experiences of authentic connection. Using leading research in psychology and neuroscience, these experiences are designed to create a neurochemical context for healing and habit-change in the brain.

**Comment by howtohumanbetter** [comment]
Detox aftercare programs that liberate humans from opioid addiction relapse cycles.

**Comment by shredtechular** [comment]
@j00bar @howtohumanbetter I believe all the changes requested in this item were completed in #37.  I think we can close this issue unless there is something else for this item that you don't see complete?
