### ISSUE TITLE
create financials page under "about us"

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#33]
page that shows total direct contributions, total donations, and total expenses

**Comment by shredtechular** [comment]
Is there any specific data/content that should be on this new page?  Or is this task really just about creating the page initially and then filling in content for total direct contributions, total donations, and total expenses later?

**Comment by howtohumanbetter** [comment]
@shredtechular that's correct, there is no content yet. We just need the page there and for now it can just say, maybe in light italics: "First year fiscal data will be available in Q2 2018. Please email kyla@seekhealing.org for documentation of your tax-deductible donation."

Once we actually have data I envision this page as simply a list of downloadable PDFs, like many charities make available on their websites for transparency purposes.
