### ISSUE TITLE
Social Media Buttons

### ISSUE THREAD

**Issue by efox27** [seekhealing/seekhealing.github.io#34]
Add LinkedIn & YouTube Buttons to website next to FB, IG and Twitter buttons at the bottom of the page.

**Comment by shredtechular** [comment]
Can you confirm the URLs for the 2 new social media buttons?  Doing a little searching I come up with the following, are these correct?

### Youtube
https://www.youtube.com/channel/UCSM8rmdOFdHop_8z2UFz5-g

### LinkedIn
https://www.linkedin.com/company/15230410/

**Comment by howtohumanbetter** [comment]
@shredtechular yes! Correct, thanks.
