### ISSUE TITLE
change to wording in hero

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#4]
Please remove: 
"Fighting the heroin & opioid epidemic with the only medicine that works for everyone: authentic connection. Find out how:"

Please replace it with: 
Making permanent lifestyle changes possible through authentic connection experiences post-detox.

**Comment by j00bar** [comment]
I'm going to suggest that we leave _something_ in the hero that says "heroin/opioid".

**Comment by howtohumanbetter** [comment]
Making permanent lifestyle changes possible through authentic connection experiences after detox from opioid & heroin addiction.

**Comment by howtohumanbetter** [comment]
**Update. New wording in the hero will be:
Unlocking the benefits of authentic connection experiences to empower sustainable healing after detox from heroin & opioid addiction.

**Comment by howtohumanbetter** [comment]
Remove "find out how:"
