### ISSUE TITLE
changes to "Volunteer" page

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#74]
**please change:**

Heading: Volunteers

"All of us can be seekers, searching for connection, for meaning, and for growth in our lives. All of us can support other seekers in their own journeys.
You can volunteer to help SeekHealing in its mission to facilitate the healing journey of seekers struggling with heroin or opioid addiction.
Whatever your background, wherever you are in live, reach out today to find out how you can help a fellow seeker through the SeekHealing project."

**to:**

Heading: General Volunteers
We are always looking for volunteers who share our vision to help support our operations. 

Right now, we're particularly in need of volunteers who have the following skills:
- accounting (specifically nonprofit or tax accounting)
- web development (proficiency in Python preferred)
- web design (able to create wire frames)
- research & data analysis (a detail oriented person who can stay on top of collecting and organizing weekly, confidential psychometric data from our pilot program participants)
- community manager (someone to help manage relationships (remotely) and triage support issues with connection agents, listeners and seekers. Communities will be managed through Facebook and private messaging)
_(last updated: January 2018)_

Please click the button below to submit an application for a general volunteering position in our organization.

button text: Apply to Volunteer [link to a general volunteering form page][I have a google form for this]

Heading: Listeners
Are you committed to constantly striving to become the best person you can be? Have you experienced firsthand how meaningful connection leads to healing and growth? 

Apply today to give the gift of listening and peer-based support to another seeker actively healing from an addiction crisis? _You don't have to have a history with chemical addiction yourself to become a Listener - just a humble awareness of your own personal growth and healing journey._

(purple bold text)January 2018 (end purple bold text): We're currently recruiting Listeners for our pilot program in Asheville, NC.
[button: Apply to Listen in Asheville, NC][link: bit.ly/seeklistening]

Heading: Questions?

info@seekhealing.org

**Comment by shredtechular** [comment]
google form link: https://docs.google.com/forms/d/e/1FAIpQLScEc_LvhC85sTBeHLUKUlEf7BG8m-kXZxJXdj9NE5uj6jmm8g/viewform

**Comment by howtohumanbetter** [comment]
Listener registation native link:
https://docs.google.com/forms/d/e/1FAIpQLSd-J3_Rz3JhZavIRLbVjkS3GkHresnEZOt96E2l5d2-4WUG7A/viewform
