### ISSUE TITLE
changes to HEAL menu + new page: Asheville Pilot Program

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#83]
Rename "Our Programs" in the nav menu to "Program Methodology" (clicking "HEAL" will still link to this page, I just want to rename it).

Please add a new page under the "Heal" menu: 
Asheville Pilot Program

Please hide the "Guidance for Detox" and "SeekConnection" pages in the HEAL nav menu

**Comment by howtohumanbetter** [comment]
The content of the Asheville Pilot Program page will be this, minus the header:
[pilot program infographic.pdf](https://github.com/seekhealing/seekhealing.github.io/files/1700019/pilot.program.infographic.pdf)

**Comment by howtohumanbetter** [comment]
Powerpoint file in case that's easier:
[pilot program infographic.pptx](https://github.com/seekhealing/seekhealing.github.io/files/1700021/pilot.program.infographic.pptx)

**Comment by howtohumanbetter** [comment]
If you need me to send you any of the native graphics let me know! If it's possible to just create a preview of the PDF file embedded in the site, maybe that would be easier for you/take less of your time?

**Comment by shredtechular** [comment]
@howtohumanbetter It is doable to embed a pdf, but I wouldn't recommend it from an SEO and user experience perspective.  Search engines won't crawl an embedded pdf's content to my knowledge and user's won't be able to click links/buttons on that pdf, not to mention different browsers could handle embedding pdf's differently.

I would recommend converting this to an actual html page.
