### ISSUE TITLE
1 - Changes to homepage

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#89]
Change to hero
please change: 
“Detox aftercare services that liberate human beings from opioid addiction relapse.”

to: 
“Free aftercare and integration services that liberate people from addiction through human connection.”

Below the Rumi quote:
please add this owl image:

Below the “About SeekHealing” paragraphs: 
please add a “Download Brochure” button that links to this PDF:

In the Asheville Pilot Program 2018 section:
Make the word “Asheville” in "Asheville Pilot Program 2018” bold and italicized like the word “SeekHealing” in the header “About SeekHealing”

In the Asheville Pilot Program 2018 section:
please change: 
Our first grassroots program begins in Asheville, NC in March 2018. Click here to learn more or sign up as a seeker or volunteer.

to: 
Our first grassroots program is underway in Asheville, NC. 

For more information about how the program works
[button] LEARN MORE

Next Listening Training: June 16-17, 2018
[button] BECOME A LISTENER

Need help now?
[button] START A CONVERSATION]

^it would be cool if these three buttons were side by side with their captions underneath

**Comment by shredtechular** [comment]
@howtohumanbetter @j00bar A few questions on this item:

---

> Below the Rumi quote:
please add this owl image:
1. I don't see an attached image to this issue?

---

>Below the “About SeekHealing” paragraphs:
please add a “Download Brochure” button that links to this PDF:

2. I don't see any PDF associated with this issue?  Or should this link to an existing PDF somewhere?

---

>For more information about how the program works
>[button] LEARN MORE
>
>Next Listening Training: June 16-17, 2018
>[button] BECOME A LISTENER
>
>Need help now?
>[button] START A CONVERSATION]

3. Can you specify what you'd like these buttons to do?  Should they link somwhere like one of the form pages or to something new?  I assume the "LEARN MORE" button should stay the same as it is on the current site and link to http://seekhealing.org/asheville-pilot-program/.  Any guidance on the other 2 buttons though?
---

**Comment by howtohumanbetter** [comment]
Hey Andrew, thanks!

- emailed you the PDF

- here is the owl:
https://drive.google.com/open?id=0B63azVj0Olu9S1hBREt3ck04bFU

- yes, the learn more button goes to the pilot program page. The “become a listener button goes to: http://bit.ly/listenAVL 
The start a conversation button goes to http://bit.ly/seekAVL

**Comment by shredtechular** [comment]
Thank you @howtohumanbetter !
