### ISSUE TITLE
3 - Changes to Asheville Pilot Program Page

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#91]
Please remove the first line of text: 
Where: Asheville, NC • When: March-Oct 2018 • Phone: 828-547-0222

Please link the words “who have been trained in the art of Listening” to the new Listening Training page.

above the “Weekly Data Collection” section:
Please add the following text, in the same purple header font as “SeekHealing Monthly Gathering” and "Weekly Data Collection”:
Weekly Group Meeting

and underneath that heading, please add the following text, in the same grey body font as the rest of the page: 
Optional weekly meeting with local partner, Original Recovery [link to http://originalrecovery.org] : a different kind of meeting where you write your own rules for your recovery. 

Please change the button text for the buttons at the bottom of this page:
change BIT.LY/SEEKAVL to START A CONVERSATION
change BIT.LY/LISTENAVL to BECOME A LISTENER
change BIT.LY/CONNECTAVL to OFFER YOUR SERVICES

Then, below the line that reads: "SeekHealing is a 501(c)3 non-profit...."
please add a DONATE button that links to http://seekhealing.kindful.com

**Comment by shredtechular** [comment]
@howtohumanbetter quick question for you:

>Please link the words “who have been trained in the art of Listening” to the new Listening Training page.

Is [http://bit.ly/listenAVL](http://bit.ly/listenAVL) the "new Listening Training page"?

**Comment by shredtechular** [comment]
As this issue depends on the new Listening Training Page to exist, putting this item on hold until #102 is reviewed and merged.
